SELECT
    p.ZUUID As Id,
	p.ZAUTHOR,
	p.ZTITLE As Podcast,
	e.ZEPISODENUMBER As EpisodeNumber,
	e.ZTITLE As Episode,
	e.ZPUBDATE,
	e.ZIMPORTDATE,
	e.ZMETADATATIMESTAMP,
	e.ZASSETURL As Url
from ZMTEPISODE e
join ZMTPODCAST p
    on e.ZPODCASTUUID = p.ZUUID
where
	e.ZASSETURL IS NOT NULL
	AND e.ZASSETURL LIKE '%Container%'
    AND p.ZUUID IN @Ids
order by p.ZUUID, e.ZPUBDATE DESC;