SELECT
	p.ZAUTHOR,
	p.ZTITLE As Podcast,
	e.ZEPISODENUMBER As EpisodeNumber,
	e.ZTITLE As Episode,
	e.ZPUBDATE,
	e.ZIMPORTDATE,
	e.ZMETADATATIMESTAMP,
	e.ZASSETURL
from ZMTEPISODE e
join ZMTPODCAST p
    on e.ZPODCASTUUID = p.ZUUID
where
	ZASSETURL NOTNULL
	AND ZASSETURL LIKE '%Container%'
order by e.ZPUBDATE;